calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quizzes/', include('quizzes.urls'))
]

quizzes/urls.py
from django.urls import path
from . import views

app_name = 'quizzes'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),

    path('new/', views.new, name='new'),
    path('check/', views.check, name='check'),
]

quizzes/models.py
from django.db import models

# Create your models here.
class Calculator(models.Model):
    num1 = models.IntegerField
    op = models.TextField
    num2 = models.IntegerField
    output = models.IntegerField
    created_at = models.DateTimeField(auto_now_add=True)

quizzes/views.py
from django.shortcuts import render, redirect
from .models import Calculator

# Create your views here.

def index(request):
    quizzes = Calculator.objects.all()

    context = {
        'quizzes': quizzes
    }

    return render(request, 'index.html', context)


def history(request):
    quizzes = Calculator.objects.all()

    context = {
        'quizzes': quizzes
    }

    return render(request, 'history.html', context)


def new(request): 
    return render(request, 'new.html')


def check(request):
    # num1 = request.POST.get('num1')
    # num2 = request.POST.get('num2')
    # op = request.POST.get('op')
    # if op == '+':
    #     output = num1 + num2
    # elif op == 

    return render(request, 'check.html')

quizzes/templates/check.html
{% extends 'base.html' %}

{% block body %}


{% endblock %}

quizzes/templates/history.html
{% extends 'base.html' %}

{% block body %}
    <div class="card mt-4">
        <div class="card-header">
            {{ quiz.id }}
        </div>

        <div class="card-body">
            {{ quiz.num1 }}
        </div>
        <div class="card-body">
            {{ quiz.op }}
        </div>
        <div class="card-body">
            {{ quiz.num2 }}
        </div>
        <div class="card-body">
            {{ quiz.output }}
        </div>
        <div class="card-footer">
            {{ article.created_at }}
        </div>
    </div>
{% endblock %}

quizzes/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <table class="table mt-4" >
        <thead>
            <tr>
                <th>#</th>
                <th>Quiz</th>
                <th>Answer</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quizzes %}
            <tr>
                <td>{{quiz.id}}</td>
                <td>{{quiz.num1}} {{quiz.op}} {{quiz.num2}}</td>
                <td><a href="{% url 'quizzes:answer' id=quiz.id %}"></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

quizzes/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'quizzes:check' %}" class="mt-4" method="POST">
        {% csrf_token %}

        <label for="">MAKE A NEW QUIZ AND SOLVE IT!</label>
        <div class="row">

            <div class="col mt-3">
            <input type="number" class="form-control" placeholder="Number 1" aria-label="num1">
            </div>

            <div class="dropdown mt-3">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Signs
                </button>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">+</a></li>
                <li><a class="dropdown-item" href="#">-</a></li>
                <li><a class="dropdown-item" href="#">×</a></li>
                <li><a class="dropdown-item" href="#">÷</a></li>
                </ul>
            </div>

            <div class="col mt-3">
            <input type="number" class="form-control" placeholder="Number 2" aria-label="num2">
            </div>

            </div>
            <label for="mt-3">=</label>
            <div class="col mt-3">
            <input type="number" class="form-control" placeholder="Answer" aria-label="num2">
            </div>

            <input type="submit" class="btn btn-primary mt-3">
            
        </div>

    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">        
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'quizzes:index' %}">Welcome to KC's Math Quiz</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'quizzes:new' %}">New Quiz</a>
                <a class="nav-link active" aria-current="page" href="{% url 'quizzes:history' %}">History</a>
            </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>